import React from 'react';

export default function TermsServicesPage() {
  return (
    <div className="bg-white min-h-screen py-8 sm:py-12 px-5 sm:px-5 [&_ul]:-indent-[1.3em]">
      <div className="max-w-7xl mx-auto flex flex-col gap-6 sm:gap-8 lg:gap-10 tracking-wider">
        <p className='!text-2xl sm:!text-3xl font-bold'>Terms and Condition</p>
        <p className="!text-2xl sm:!text-3xl lg:!text-3xl font-bold">Terms of Services</p>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold mt-4 sm:mt-6">Who We Are</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>{import.meta.env.VITE_COMPANY_NAME} ("we," "us," or "our") operates the website {import.meta.env.VITE_DOMAIN_NAME}/ (the "Site"). We are dedicated to providing high-quality e-commerce products and services. This document outlines the terms and conditions governing your use of our Site.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Acceptance of Terms</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>By accessing and using our Site, you confirm that you agree to comply with these Terms of Service. If you do not agree to these terms, please do not use our Site. We reserve the right to modify these terms at any time and continued use of the Site after such changes will constitute your acceptance of the new terms.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">License to Use Our Site</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>Subject to your compliance with these Terms, we grant you a revocable, non-exclusive, non-transferable license to access and use our Site for personal, non-commercial purposes.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Definitions
          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base !pb-4'>To help explain things as clearly as possible in these General Terms and Conditions, every time any of these terms are referenced, they are strictly defined as:</p>
          <ul className="!list-disc !list-inside text-gray-700 space-y-2 !text-sm sm:!text-base !pl-6 lg:!pl-8">
            <li>Cookie: A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you, such as your language preference or login information.</li>
            <li>Company: When this policy mentions "Company," "we," "us," or "our," it refers to {import.meta.env.VITE_COMPANY_NAME}, {import.meta.env.VITE_COMPANY_ADDRESS}, which is responsible for your information under these General Terms and Conditions.</li>
            <li>Country: The location where {import.meta.env.VITE_COMPANY_NAME} or the owners/founders of {import.meta.env.VITE_COMPANY_NAME} are based.</li>
            <li>Device: Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit {import.meta.env.VITE_COMPANY_NAME} and use the services.</li>
            <li>Service: Refers to the services provided by {import.meta.env.VITE_COMPANY_NAME} as described in the relevant terms (if available) and on this platform.</li>
            <li>Third-party service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
            <li>Website: {import.meta.env.VITE_COMPANY_NAME}'s site, which can be accessed via this URL: {import.meta.env.VITE_DOMAIN_NAME}/.</li>
            <li>You: A person or entity that is registered with {import.meta.env.VITE_COMPANY_NAME} to use the Services.</li>
          </ul>
        </div>

        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">User Responsibilities
          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base !pb-4'>You agree to:</p>
          <ul className="!list-disc !list-inside text-gray-700 space-y-2 !text-sm sm:!text-base !pl-6 lg:!pl-8">
            <li>Provide accurate, current, and complete information when creating an account or placing an order.</li>
            <li>Maintain the security of your account by protecting your password and restricting access to your account.</li>
            <li>Notify us immediately of any unauthorized use of your account or any other breach of security.</li>
            <li>Accept responsibility for all activities that occur under your account.</li>
          </ul>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Restrictions
          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base !pb-4'>You agree not to, and you will not permit others to:</p>
          <ul className="!list-disc !list-inside text-gray-700 space-y-2 !text-sm sm:!text-base !pl-6 lg:!pl-8">
            <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the website or make the platform available to any third party.</li>
            <li>Modify, make derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the website.</li>
            <li>Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of {import.meta.env.VITE_COMPANY_NAME} or its affiliates, partners, suppliers, or the licensors of the website.</li>
          </ul>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Information We Collect

          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base !pb-4'>We may collect personal information when you:</p>
          <ul className="!list-disc !list-inside text-gray-700 space-y-2 !text-sm sm:!text-base !pl-6 lg:!pl-8">
            <li>Create an account</li>
            <li>Place an order</li>
            <li>Subscribe to our newsletter</li>
            <li>Contact customer service</li>
          </ul>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Types of Information Collected:


          </h2>
          <ul className="!list-disc !list-inside text-gray-700 space-y-2 !text-sm sm:!text-base !pl-6 lg:!pl-8">
            <li>Personal Identification Information: Name, email address, mailing address, and phone number.</li>
            <li>Payment Information: Credit card details are processed securely through third-party payment processors.</li>
            <li>Non-Personal Identification Information: Browser type, device type, IP address, pages visited, and time spent on the site.</li>
          </ul>
        </div>

        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Return and Refund Policy</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>If you are not satisfied with your purchase, please contact us via {import.meta.env.VITE_CUSTOMER_SUPPORT_EMAIL} within 14 days for returns or exchanges. Products must be returned in original condition and packaging.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Limitation of Liability</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>Under no circumstances shall {import.meta.env.VITE_COMPANY_NAME} be liable for any direct, indirect, incidental, special, or consequential damages resulting from your use of the Site or any products purchased through it.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Indemnification</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>You agree to indemnify, defend, and hold harmless {import.meta.env.VITE_COMPANY_NAME}, its affiliates, and employees from any claims, losses, liabilities, damages, or expenses (including reasonable attorney fees) arising out of your use of the Site or violation of these Terms.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Your Suggestions</h2>
          <div className='flex flex-col gap-4'>

            <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>Any feedback, comments, ideas, improvements, or suggestions (collectively, "Suggestions") provided by you to {import.meta.env.VITE_COMPANY_NAME} regarding the website shall remain the sole and exclusive property of {import.meta.env.VITE_COMPANY_NAME}.</p>
            <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>{import.meta.env.VITE_COMPANY_NAME} shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or compensation to you.
            </p>
          </div>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Your Consent</h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>We've updated our General Terms and Conditions to provide you with complete transparency regarding what is set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our General Terms and Conditions.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Links to Other Websites
          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>These General Terms and Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by {import.meta.env.VITE_COMPANY_NAME}. We are not responsible for the content, accuracy, or opinions expressed in such websites, and such websites are not investigated, monitored, or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our General Terms and Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">COOKIES
          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>{import.meta.env.VITE_COMPANY_NAME} uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionalities like videos may become unavailable, or you would be required to enter your login details every time you visit the website, as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place personally identifiable information in Cookies.</p>
        </div>
        <div>
          <h2 className="!text-xl sm:!text-2xl font-semibold">Changes to These Terms
          </h2>
          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base'>We may update these Terms of Service from time to time. Any changes will be posted on this page with an updated effective date. We encourage you to review these Terms periodically to stay informed about your rights and obligations.</p>
        </div>

        <div >
          <h2 className="!text-xl sm:!text-2xl font-semibold">Contact Us</h2>

          <p className='leading-6 sm:leading-7 !text-sm sm:!text-base pb-4'>If you have any questions about these Terms of Service, please contact us at:</p>
          <p className='flex flex-col gap-2 !text-sm sm:!text-base'>
            <span className="break-words"> Email: <a href={`mailto:${import.meta.env.VITE_CUSTOMER_SUPPORT_EMAIL || 'Email Not Set'}`} className="underline underline-offset-4 break-all">{import.meta.env.VITE_CUSTOMER_SUPPORT_EMAIL}</a></span>
            <span>
              Phone: <a href={`tel:${import.meta.env.VITE_CUSTOMER_SERVICE_PHONE || 'Phone Not Set'}`} className="underline underline-offset-4">{import.meta.env.VITE_CUSTOMER_SERVICE_PHONE}</a>
            </span>
            <span className="break-words"> Address: {import.meta.env.VITE_COMPANY_ADDRESS}, USA</span>
            <span>
              Website: <a href={`${import.meta.env.VITE_DOMAIN_NAME}`} target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">{import.meta.env.VITE_STORE_NAME}.com</a>
            </span>
            <span className='pt-4'>
              Last Updated: 1-7-2025
            </span>
          </p>
        </div>
      </div>
    </div>
  );
} 